import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { copyFile, mkdir, rm } from 'node:fs/promises';
import path from 'node:path';
import { lazyImagePlugin } from './build/lazy-image-plugin.mjs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const outputDirectory = path.resolve(process.argv[3] ?? 'dist');
const defaultOutputDirectory = path.resolve('dist');

if (outputDirectory === defaultOutputDirectory) {
	await rm(outputDirectory, { recursive: true, force: true });
}
await mkdir(outputDirectory, { recursive: true });
await Promise.all([
	copyFile('manifest.json', path.join(outputDirectory, 'manifest.json')),
	copyFile('styles.css', path.join(outputDirectory, 'styles.css')),
]);

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	plugins: [lazyImagePlugin()],
	outfile: path.join(outputDirectory, 'main.js'),
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
